const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const dotenv = require('dotenv');
dotenv.config();
const authRoutes = require('./routes/authRoutes');
const jobRoutes = require('./routes/jobRoutes');
const chatRoutes = require('./routes/chatRoutes');
const walletRoutes = require('./routes/walletRoutes');
const notificationRoutes = require('./routes/notificationRoutes');
const adminRoutes = require('./routes/adminRoutes');
const app = express();
app.use(helmet());
app.use(cors());
app.use(morgan('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use('/api/auth', authRoutes);
app.use('/api/jobs', jobRoutes);
app.use('/api/chat', chatRoutes);
app.use('/api/wallet', walletRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/admin', adminRoutes);
app.get('/', (req, res) => { res.json({ message: '🇿🇦 Umsebenzi API is running!', version: '1.0.0', status: 'online', endpoints: { auth: '/api/auth', jobs: '/api/jobs', chat: '/api/chat', wallet: '/api/wallet', notifications: '/api/notifications', admin: '/api/admin' } }); });
app.use((req, res) => { res.status(404).json({ success: false, message: 'Route not found' }); });
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => { console.log('✅ Umsebenzi server running on port ' + PORT); });
module.exports = app;